# Generated by Django 3.2.3 on 2021-05-31 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='model',
            field=models.ForeignKey(limit_choices_to={'mark': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.mark')}, on_delete=django.db.models.deletion.CASCADE, to='cars.model'),
        ),
    ]
