version: "3"
services:
    web:
        build: ./jdmcars
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./jdmcars/:/usr/src/jdmcars/
        ports: 
            - 8000:8000
        env_file: 
            - ./.env.dev
        depends_on: 
            - db
    db:
        image: postgres:12.0-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=jdmdb
volumes: 
    postgres_data: